---
  handlers:
    -
      static_files: cert.der-web/dist/\1
      upload: cert.der-web/dist/(.*\..+)$
      url: /(.*\..+)$
    -
      static_files: cert.der-web/dist/index.html
      upload: cert.der-web/dist/index.html
      url: /.*
  runtime: nodejs10
