---
  steps:
    -
      args:
        - install
      entrypoint: npm
      name: "node:10.15.1"
    -
      args:
        - run
        - build
      entrypoint: npm
      name: "node:10.15.1"
    -
      args:
        - app
        - deploy
      name: gcr.io/cloud-builders/gcloud
  timeout: 1600s
